site_name: sql-unit-test Docs

# Theme Configuration 

theme:
  name: material
  logo: assets/sql-unit-test_logo.svg
  icon:
    edit: material/pencil-box-multiple
    view: material/file-eye
    repo: fontawesome/brands/github
  font:
    text: JetBrains Mono
    code: JetBrains Mono
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: orange
      toggle:
        icon: material/lightbulb-off
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/lightbulb-on
        name: Switch to light mode
    

  features:
    - navigation.tabs
    - toc.follow
    - navigation.top
    - navigation.path
    - navigation.footer
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tooltips

# Plugin Configuration

plugins:
  - search

# Extension Configuration

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr


extra_css:
  - stylesheets/extra.css

# Repository Configuration

repo_url: https://github.com/cohenj20/sql-unit-test

repo_name: cohenj20/sql-unit-test

edit_uri: edit/main/docs/

